apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-platform-app-config
data:
  APP_ENV: dev
  APP_VERSION: "1.1.1"
  DB_HOST: replace-with-rds-endpoint.invalid
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_CONNECT_TIMEOUT: "5"
  DB_SECRET_ARN: arn:aws:secretsmanager:ap-south-1:000000000000:secret:REPLACE_WITH_APPLICATION_DATABASE_SECRET
